### ISSUE TITLE
Rustyloader wrong tests

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-SdE2/questions#119]
From `classroom.yml`:

```yaml
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: build
      id: build
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: build
        setup-command: rustup target add i686-unknown-linux-gnu && sudo apt-get update
          && sudo apt-get -y install gcc-multilib
        command: cargo install --path .
        timeout: 10
    - name: setup
      id: setup
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: setup
        setup-command: git clone https://github.com/UPB-FILS-SdE2/devoir-3-tests.git
        command: cd devoir-3-tests/inputs && make
        timeout: 10
```

https://github.com/UPB-FILS-SdE2/devoir-3-tests leads to the last year's scheduler tests
